<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
		<link rel="stylesheet" href="assets/styles/css/style.css">
	</head>
	<body>
		<header>
		    <img src="assets/svg/onevent-white.svg"></img>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
					<li>
					    <a href="index.php?route=contact">Contact</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if($route === "home"){
			    require "templates/home.phtml"; 
			}
			else if($route === "about"){
			    require "templates/about.phtml"; 
			}
			else if($route === "contact"){
			    require "templates/contact.phtml";
			}
			else if($route === "notFound"){
			    require "templates/notFound.phtml";
			}
		?>
	</body>
</html>