<main class="main home">
    <div class="container home-text">
        <h1>YEPIFY</h1>
        <h2>Les meilleurs Yep, partout, tout le temps</h2>
    </div>
    <div class="card">
        <header class="card-header">
            <div class="text-card-header">
                <p>Yeppy Yeah</p>
                <h3>I'm feeling Yep</h3>
            </div>
            <img src="assets/styles/img/tree.png"></img>
        </header>
        <div class="list-card">
            <figure class="song">
                <img src="assets/styles/img/equalizer.png" alt="Play button">
                <p>Yeppin'on a prayer</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Yep it be</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Yeppin on th dock of the bay</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Because the yep</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Leaving Las Yepas</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Enter Yepman</p>
            </figure>
            <figure class="song">
                <img src="assets/styles/img/play.png" alt="Play button">
                <p>Fear of the yep</p>
            </figure>
        </div>
    </div>
</main>