<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Yepify</title>
    <link rel="stylesheet" href="assets/styles/css/style.css" type="text/css" />
</head>
<body>
    <header class="header">
        <ul>
            <li><a href="index.php">Accueil</a></li>
            <li><a href="index.php?route=nos-tarifs">Tarifs</a></li>
        </ul>
    </header>
    <?php
        if($route === "nos-tarifs"){
            require "templates/tarifs.phtml";
        }
        else if($route === "notFound"){
            require "templates/notFound.phtml";
        }
        if($route === "home"){
            require "templates/home.phtml";
        }
    ?>
</body>
</html>