<main class="main-column">
    <h1>Choisissez votre formule</h1>
    <div class="cards-tarifs">
        <div class="card-tarifs-4">
            <h4>Basic</h4>
            <ul>
                <li>Une publicité tous les 3 Yep</li>
                <li>Zapping 6 Yep par heure</li>
                <li>Créez vos Yeplist</li>
                <li>Partagez vos Yeplist</li>
            </ul>
            <p>3.99 $ / mois</p>
        </div>
        <div class="card-tarifs">
            <h4>Premium</h4>
            <ul>
                <li>Une publicité tous les 20 Yep</li>
                <li>Zapping de Yep illimité</li>
                <li>Créez vos Yeplist</li>
                <li>Créez des Yeplist collaboratives</li>
                <li>Envoyez des yeps anonymes</li>
                <li>Mini studio de création de Yep</li>
            </ul>
            <p>9.99 $ / mois</p>
        </div>
        <div class="card-tarifs-6">
            <h4>Pro</h4>
            <ul>
                <li>Une publicité tous les 20 Yep</li>
                <li>Zapping de Yep illimité</li>
                <li>Créez vos Yeplist</li>
                <li>Créez des Yeplist collaboratives</li>
                <li>Publiez vos Yep persos</li>
                <li>Gagnez des royalties sur vos Yep</li>
            </ul>
            <p>15.99 $ / mois</p>
        </div>
    </div>
</main>